---
title: "SUBMISSION"
author: "Eric Griff"
date: "Tuesday, May 19, 2015"
output: html_document
---

# Visual of my cachematrix.R in action.

This is not the part to be evaluated, rather [cachematrix.R][1] is. This is my application
of what I have learned from other classes I am taking that are quite informative
as well.

## The function definitions

```{r}
## These 2 functions set a cache of a matrix, and then calculate the
## inverse of it.

## This function returns the passed matrix as a functional cache

makeCacheMatrix <- function(x = matrix()) {
        s <- NULL
        set <- function(y) {
                x <<- y
                s <<- NULL
        }
        get <- function() x
        setsolve <- function(solve) s <<- solve
        getsolve <- function() s
        list(set=set, get=get,
             setsolve=setsolve,
             getsolve=getsolve)
}


## This function solves, then caches the resulting inverse matrix on the first
## call. Subsequent calls return the cached result.

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
        s <- x$getsolve()
        if(!is.null(s)) {
                message("getting cached data")
                return(s)
        }
        data <- x$get()
        s <- solve(data, ...)
        x$setsolve(s)
        s
}
```

# Test Run

I got this test data at [Mathwords: Inverse of a Matrix][2].

```{r}
m <- matrix(c(4,3,3,2),2,2)
cm <- makeCacheMatrix(m)
cacheSolve(cm)
```

[1]: https://github.com/setjmp2013/ProgrammingAssignment2/blob/master/cachematrix.R "cachematrix.R"
[2]: http://www.mathwords.com/i/inverse_of_a_matrix.htm "Mathwords: Inverse of a Matrix"